#! /bin/sh

bspc monitor -d files web telegram music desktop1 desktop2 desktop3 desktop4

bspc config border_width           2
bspc config window_gap             5
bspc config focus_follows_pointer  true
bspc config split_ratio            0.5
bspc config borderless_monocle     true
bspc config gapless_monocle        true

bspc rule -a Nemo                   desktop='files'       follow=on
bspc rule -a Thunar                 desktop='files'       follow=on
bspc rule -a Firefox                desktop='web'         follow=on
bspc rule -a Chromium               desktop='web'         follow=on
bspc rule -a TelegramDesktop        desktop='telegram'    follow=on
bspc rule -a URxvt:ranger           desktop='files'       follow=on
bspc rule -a URxvt:ncmpcpp          desktop='music'       follow=on  rectangle=680x300+520+134  state=floating 
bspc rule -a URxvt:cava             desktop='music'       follow=on  rectangle=1010x200+190+464  state=floating
bspc rule -a URxvt:album_art        desktop='music'       follow=on  rectangle=300x300+190+134  state=floating

bspc rule -a Lxappearance           state=floating 
bspc rule -a Tk                     state=floating
bspc rule -a Unetbootin.elf         state=floating
bspc rule -a Transmission-gtk       state=floating
bspc rule -a Gnome-system-monitor   state=floating
bspc rule -a Zathura                state=fullscreen
bspc rule -a mpv                    state=fullscreen

compton --backend glx --vsync opengl-swc -b &
sxhkd &
mpd &

wal -i ~/Wallpapers/japan.jpg -a 90 --saturate 0.2

. $HOME/.zshrc

$BSPWM/polybar.sh
#$BSPWM/workflow.sh

# Switch keyboard layout
setxkbmap -layout us,ru
setxkbmap -option 'grp:alt_shift_toggle'

# colorscheme (wal)
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
